
services:
    app:
        image: matheusbrdev/php-fpm:8.3
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html

    server:
        image: nginx:1.27-alpine
        container_name: server
        restart: unless-stopped
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - ./environment-files/nginx:/etc/nginx/conf.d
            - ./:/var/www/html